{"name": "测试用例描述：错误的账号登录失败", "status": "passed", "description": "测试描述：错误的账号登录失败", "steps": [{"name": "输入错误的账号", "status": "passed", "attachments": [{"name": "错误的账号", "source": "0c110818-7f5c-4126-989a-85cf062a67bb-attachment.attach"}], "start": 1651989259167, "stop": 1651989259168}], "attachments": [{"name": "截图", "source": "1916c9f2-082a-4df8-b7aa-d2ddcfea1ff9-attachment.png", "type": "image/png"}, {"name": "截图", "source": "50a83d0c-b80a-4284-9a42-0606dc7c1421-attachment.png", "type": "image/png"}], "start": 1651989259167, "stop": 1651989266142, "uuid": "ecc5473d-075c-4b1d-b034-a0699ae9917c", "historyId": "07ccc934c01f5e078d85f2f38ccbb5fd", "testCaseId": "07642125497ce5d4c888927c76cac843", "fullName": "test_two.Test#test_21", "labels": [{"name": "severity", "value": "critical"}, {"name": "feature", "value": "登录模块"}, {"name": "epic", "value": "xxx测试"}, {"name": "story", "value": "登录"}, {"name": "suite", "value": "test_two"}, {"name": "subSuite", "value": "Test"}, {"name": "host", "value": "MS-SLSXLICKSUSF"}, {"name": "thread", "value": "15092-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_two"}]}