{"name": "test_login", "status": "broken", "statusDetails": {"message": "IndexError: list index out of range", "trace": "self = <testcase.test_login_demo.TestLogin object at 0x000002E842BB5828>\n\n    def test_login(self):\n        for i in range(1,10):\n>           if (excel[i]['是否执行']) != 'Y':\nE           IndexError: list index out of range\n\ntest_login_demo.py:20: IndexError"}, "start": 1656905704398, "stop": 1656905704408, "uuid": "ea22451a-7676-46c6-a77b-63c2bf12217d", "historyId": "966da4c978c322b6b1d09eb1e0322926", "testCaseId": "635f167e9ec99310021d4ad82ace208f", "fullName": "test_login_demo.TestLogin#test_login", "labels": [{"name": "suite", "value": "test_login_demo"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "MS-SLSXLICKSUSF"}, {"name": "thread", "value": "28668-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login_demo"}]}