{"name": "测试用例描述：错误的验证码登录失败", "status": "passed", "description": "测试描述：错误的验证码登录失败", "steps": [{"name": "输入正确账号", "status": "passed", "attachments": [{"name": "正确账号", "source": "1d7ffa62-d834-4e50-bfea-4dd364e3b2ca-attachment.attach"}], "start": 1651818009551, "stop": 1651818009551}, {"name": "输入正确密码", "status": "passed", "attachments": [{"name": "正确密码", "source": "2ae6e6d0-310d-43ed-8374-3eded0ba6802-attachment.attach"}], "start": 1651818009598, "stop": 1651818009598}, {"name": "输入错误验证码", "status": "passed", "attachments": [{"name": "验证码为空", "source": "42f48091-fb3e-43ff-ae09-46ee91a686d7-attachment.attach"}], "start": 1651818009652, "stop": 1651818009655}], "attachments": [{"name": "截图", "source": "3b47078c-fd0a-41f5-805d-bf10fc2b2d37-attachment.png", "type": "image/png"}], "start": 1651818009550, "stop": 1651818012383, "uuid": "43f76649-0ed3-44bb-b76e-02697fc6f2fc", "historyId": "99cc6b199ab7eac5979ecaecd144eda1", "testCaseId": "44097febf60fbfed56a361cecfc05a9e", "fullName": "test_two.Test#test_07", "labels": [{"name": "epic", "value": "xxx测试"}, {"name": "story", "value": "登录"}, {"name": "severity", "value": "critical"}, {"name": "feature", "value": "登录模块"}, {"name": "suite", "value": "test_two"}, {"name": "subSuite", "value": "Test"}, {"name": "host", "value": "MS-SLSXLICKSUSF"}, {"name": "thread", "value": "2072-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_two"}]}