{"name": "测试用例描述：错误的密码登录失败", "status": "passed", "description": "测试描述：错误的密码登录失败", "steps": [{"name": "输入错误的密码", "status": "passed", "attachments": [{"name": "错误的密码", "source": "0f07a36c-138c-4796-8d92-d9e4a20b1343-attachment.attach"}], "start": 1651989229079, "stop": 1651989229079}], "attachments": [{"name": "截图", "source": "b0b93464-bbd5-4b9d-8b1e-8aae5793e2e1-attachment.png", "type": "image/png"}, {"name": "截图", "source": "1a510cc4-fa83-4fd0-bc4b-395e1b60a995-attachment.png", "type": "image/png"}], "start": 1651989229079, "stop": 1651989230783, "uuid": "fb5471ff-ec05-4127-a480-f7d08058e24f", "historyId": "e042998cd34bf7d92d802f115102d44e", "testCaseId": "ce17e49339328b1be4c6805d1bcb9a3f", "fullName": "test_two.Test#test_22", "labels": [{"name": "feature", "value": "登录模块"}, {"name": "story", "value": "登录"}, {"name": "epic", "value": "xxx测试"}, {"name": "severity", "value": "critical"}, {"name": "suite", "value": "test_two"}, {"name": "subSuite", "value": "Test"}, {"name": "host", "value": "MS-SLSXLICKSUSF"}, {"name": "thread", "value": "15172-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_two"}]}