{"name": "测试用例描述：错误的验证码登录失败", "status": "passed", "description": "测试描述：错误的验证码登录失败", "steps": [{"name": "输入错误的验证码", "status": "passed", "attachments": [{"name": "错误的验证码", "source": "844d1847-294a-45da-b3b3-a43df70ee24d-attachment.attach"}], "start": 1651988651104, "stop": 1651988651104}], "attachments": [{"name": "截图", "source": "4a051d28-730e-43c0-8efc-e16b9e5834c2-attachment.png", "type": "image/png"}, {"name": "截图", "source": "d2228162-96f4-4345-b494-c1e13d2a8cfb-attachment.png", "type": "image/png"}], "start": 1651988651104, "stop": 1651988652303, "uuid": "92de1a2e-0380-4bc7-abc2-b1e240f3fcc0", "historyId": "2d7cab507b6851b7595fa5868d612dc0", "testCaseId": "a971ec309964150e721c6794e448f50a", "fullName": "test_two.Test#test_23", "labels": [{"name": "epic", "value": "xxx测试"}, {"name": "feature", "value": "登录模块"}, {"name": "severity", "value": "critical"}, {"name": "story", "value": "登录"}, {"name": "suite", "value": "test_two"}, {"name": "subSuite", "value": "Test"}, {"name": "host", "value": "MS-SLSXLICKSUSF"}, {"name": "thread", "value": "17840-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_two"}]}