{"name": "测试用例描述：错误的账号登录失败", "status": "passed", "description": "测试描述：错误的账号登录失败", "steps": [{"name": "输入错误账号", "status": "passed", "attachments": [{"name": "错误账号", "source": "4a25a265-7d37-4c8c-8804-b00b7c255be6-attachment.attach"}], "start": 1651818987143, "stop": 1651818987143}, {"name": "输入正确密码", "status": "passed", "attachments": [{"name": "正确密码", "source": "7ea85221-42f5-41b5-bb36-55be12bd905d-attachment.attach"}], "start": 1651818987185, "stop": 1651818987185}, {"name": "输入正确验证码", "status": "passed", "attachments": [{"name": "正确验证码", "source": "64100e8f-b933-457a-84ea-8c4e799a0c6f-attachment.attach"}], "start": 1651818987239, "stop": 1651818987240}], "attachments": [{"name": "截图", "source": "2b54cd8c-d835-48f8-bd7b-ca92567c6c46-attachment.png", "type": "image/png"}], "start": 1651818987143, "stop": 1651818989560, "uuid": "90cb7fd9-d82a-4354-b6f3-e247bbd44f3a", "historyId": "24e424fe5694bafaaba56099b659de37", "testCaseId": "938631cc2602a20c3281e7f98df5b2bf", "fullName": "test_two.Test#test_05", "labels": [{"name": "story", "value": "登录"}, {"name": "epic", "value": "xxx测试"}, {"name": "feature", "value": "登录模块"}, {"name": "severity", "value": "critical"}, {"name": "suite", "value": "test_two"}, {"name": "subSuite", "value": "Test"}, {"name": "host", "value": "MS-SLSXLICKSUSF"}, {"name": "thread", "value": "9800-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_two"}]}