WARNING  urllib3.connectionpool:connectionpool.py:752 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022027A28DD8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)': /session/6388f8ba5bbdae9cc7dbeff54b8ac26c/url
WARNING  urllib3.connectionpool:connectionpool.py:752 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022027A707B8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)': /session/6388f8ba5bbdae9cc7dbeff54b8ac26c/url
WARNING  urllib3.connectionpool:connectionpool.py:752 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022027A706D8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)': /session/6388f8ba5bbdae9cc7dbeff54b8ac26c/url