{"uuid": "0f581004-6b43-4ee6-9d18-c2521d489dae", "children": ["36551391-e53f-4b3f-9cbb-d55ce40cc60e"], "befores": [{"name": "xunit_setup_class_fixture_Test", "status": "broken", "statusDetails": {"message": "AttributeError: type object 'Test' has no attribute 'driver'\n", "trace": "  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\_pytest\\python.py\", line 811, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\_pytest\\python.py\", line 739, in _call_with_optional_argument\n    func(arg)\n  File \"C:\\Users\\Administrator\\.jenkins\\workspace\\psimsendemail\\untitled\\testcase\\test_four.py\", line 24, in setup_class\n    cls.driver.implicitly_wait(20)\n"}, "start": 1651835600118, "stop": 1651835600118}], "start": 1651835600118, "stop": 1651835600149}