{"name": "测试用例描述：错误的验证码登录失败", "status": "passed", "description": "测试描述：错误的验证码登录失败", "steps": [{"name": "输入错误的验证码", "status": "passed", "attachments": [{"name": "错误的验证码", "source": "2884a3db-87d2-476a-a45f-334ecaec6494-attachment.attach"}], "start": 1651988424351, "stop": 1651988424351}], "attachments": [{"name": "截图", "source": "e5e3ee4d-465d-4fee-81e7-10960d2c6960-attachment.png", "type": "image/png"}, {"name": "截图", "source": "b2a0779a-7f69-4209-b12d-3ad2743eab06-attachment.png", "type": "image/png"}], "start": 1651988424351, "stop": 1651988425562, "uuid": "14aad874-5293-472b-aec8-a05976878a3a", "historyId": "2d7cab507b6851b7595fa5868d612dc0", "testCaseId": "a971ec309964150e721c6794e448f50a", "fullName": "test_two.Test#test_23", "labels": [{"name": "feature", "value": "登录模块"}, {"name": "epic", "value": "xxx测试"}, {"name": "story", "value": "登录"}, {"name": "severity", "value": "critical"}, {"name": "suite", "value": "test_two"}, {"name": "subSuite", "value": "Test"}, {"name": "host", "value": "MS-SLSXLICKSUSF"}, {"name": "thread", "value": "14400-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_two"}]}