{"name": "测试用例描述：错误的验证码登录失败", "status": "passed", "description": "测试描述：错误的验证码登录失败", "steps": [{"name": "输入错误的验证码", "status": "passed", "attachments": [{"name": "错误的验证码", "source": "b0669243-bd28-4a0e-afe0-475458006339-attachment.attach"}], "start": 1658301812526, "stop": 1658301812526}], "attachments": [{"name": "截图", "source": "98fb5321-6015-4db3-a931-fb1840428908-attachment.png", "type": "image/png"}], "start": 1658301812526, "stop": 1658301813588, "uuid": "b40e90c0-2b26-491a-9075-49bf29ba26a3", "historyId": "6c05533b4213c6c9c25514ab7813de92", "testCaseId": "638baadf0fe36cf4b1b76169efb70edf", "fullName": "test_login.Test#test_23", "labels": [{"name": "severity", "value": "critical"}, {"name": "feature", "value": "登录模块"}, {"name": "story", "value": "登录"}, {"name": "epic", "value": "xxx测试"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Test"}, {"name": "host", "value": "MS-SLSXLICKSUSF"}, {"name": "thread", "value": "4472-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login"}]}