WARNING  urllib3.connectionpool:connectionpool.py:752 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CF09A48E48>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)': /session/e4e9d40a7b7e7862f3a959f81ef2c2c1/url
WARNING  urllib3.connectionpool:connectionpool.py:752 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CF09A91A20>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)': /session/e4e9d40a7b7e7862f3a959f81ef2c2c1/url
WARNING  urllib3.connectionpool:connectionpool.py:752 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CF09A916A0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)': /session/e4e9d40a7b7e7862f3a959f81ef2c2c1/url